version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: threads-app
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
# To Run it docker-compose -f docker-compose.dev.yml up
