version: '3.8'

services:
  nextjs-app:
    image: node:14-alpine
    working_dir: /app
    environment:
      NODE_ENV: production
    volumes:
      - ./app:/app
    command: ['npm', 'run', 'start']
    ports:
      - '3000:3000'
    depends_on:
      - nextjs-app-build

  nextjs-app-build:
    image: node:14-alpine
    working_dir: /app
    volumes:
      - ./app:/app
    command: ['npm', 'run', 'build']
